# Generated by Django 3.1.7 on 2021-05-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='roleDesc',
            field=models.CharField(max_length=50, verbose_name='角色描述'),
        ),
    ]
