# Generated by Django 3.1.7 on 2021-05-19 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='汽车ID')),
                ('cname', models.CharField(max_length=20, verbose_name='商品名称')),
                ('cbrand', models.CharField(max_length=20, verbose_name='汽车品牌')),
                ('introduce', models.CharField(max_length=50, verbose_name='简介')),
                ('pics', models.CharField(max_length=128, verbose_name='图片')),
                ('cprice', models.FloatField(verbose_name='价格')),
            ],
            options={
                'verbose_name': '汽车',
                'verbose_name_plural': '汽车',
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('fid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='工厂ID')),
                ('fname', models.CharField(max_length=20, verbose_name='工厂名称')),
                ('faddress', models.CharField(max_length=20, verbose_name='工厂地址')),
            ],
            options={
                'verbose_name': '工厂',
                'verbose_name_plural': '工厂',
                'db_table': 'factory',
            },
        ),
        migrations.CreateModel(
            name='FactoryTrade',
            fields=[
                ('ftid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('ftprice', models.FloatField(verbose_name='成交价格')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodity.car', verbose_name='厂商ID')),
            ],
            options={
                'verbose_name': '工厂购入订单',
                'verbose_name_plural': '工厂购入订单',
                'db_table': 'factory_trade_data',
            },
        ),
        migrations.CreateModel(
            name='CustomerTrade',
            fields=[
                ('ctid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('ctprice', models.FloatField(verbose_name='成交价格')),
                ('cprofit', models.FloatField(verbose_name='总利润')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodity.car', verbose_name='汽车ID')),
            ],
            options={
                'verbose_name': '客户购买订单',
                'verbose_name_plural': '客户购买订单',
                'db_table': 'customer_trade_data',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='分类ID')),
                ('cat_name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('cat_pid', models.IntegerField(verbose_name='分类父ID')),
                ('cat_level', models.IntegerField(verbose_name='分类层级')),
                ('children', models.ManyToManyField(to='commodity.Category', verbose_name='子分类集')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodity.factory', verbose_name='工厂ID'),
        ),
    ]
